pipeline {
    agent any

    environment {
        IMAGE_NAME = "secure-devsecops-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/Tris142/secure-ci-cd-devsecops-pipeline.git'
            }
        }

        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh 'sonar-scanner'
                }
            }
        }

        stage('Trivy Filesystem Scan') {
            steps {
                sh 'trivy fs --severity HIGH,CRITICAL .'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image --severity HIGH,CRITICAL $IMAGE_NAME'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f secure-devsecops || true
                docker run -d \
                --name secure-devsecops \
                -p 80:80 \
                $IMAGE_NAME
                '''
            }
        }
    }
}
