pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
           url: 'https://github.com/tris142/secure-ci-cd-devsecops-pipeline.git'
      }
    }

    stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
      }
    }
    
    stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    mvn sonar:sonar \
                    -Dsonar.projectKey=secure-app \
                    -Dsonar.host.url=http://localhost:9000
                    '''
         }
      }
   }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devsecops-app -f docker/Dockerfile .'
      }
    }

    stage('Security Scan - Trivy') {
      steps {
        sh 'trivy image devsecops-app'
      }
    }

    stage('Deploy') {
      steps {
        sh 'docker run -d -p 80:80 devsecops-app'
      }
    }
  }
}
